spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/CRM
    username: root
    password: 1234
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true