spring:
  datasource:
    driver-class-name: com.postgresql.cj.jdbc.Driver
    url: jdbc:postgresql://127.0.0.1:5432/crm
    username: myuser
    password: 1234
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true